Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/ExtraSpacing:
  Exclude:
    - spec/**/*_spec.rb

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Layout/LineLength:
  Exclude:
    - spec/**/*_spec.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Max: 12

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/AccessorGrouping:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/PercentLiteralDelimiters:
  Exclude:
    - flex-station-data.gemspec

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantPercentQ:
  Exclude:
    - flex-station-data.gemspec

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Exclude:
    - spec/**/*_spec.rb

Style/WordArray:
  Exclude:
    - spec/**/*_spec.rb
